### ISSUE TITLE
Consider how we could remove .env files from source control 

### ISSUE THREAD

**Issue by ghost** [ricado-group/cra-template#10]
To minimize the amount of setup required for a new developer and to reduce the risk of inheriting other developers setups. We'd like to consider removing the .env file from source control and have this pre-configured from new users.

A couple of options may include:

- Taking advantage of VSCode's scripts by using a combination of `tasks.json` and `settings.json` to generate these files with the click of a button in the editor.
- Generating the .env file for production during the CI Build (e.g. as part of a Github Action)
- Something else?

**Comment by ashneilson** [comment]
Ideally this file and its inputs would be managed by **@ricado/react-scripts**?

We can then provide a way for developers to adjust the configuration by defining a ```<something>.json``` config file?

**Comment by ashneilson** [comment]
Closing as this task has been completed outside of this Repo by removing the need for .env in `core-ui`
