### ISSUE TITLE
Standardise on a RICADO Core Scripts solution 

### ISSUE THREAD

**Issue by ghost** [ricado-group/cra-template#11]
Throughout many of our apps, we have NPM scripts that are repeated such as:

```json
{
  "scripts": {
    "start": "craco start",
    "build": "npm run pre-build && craco build && npm run test",
    "build:ci": "npm run build",
    "test": "craco test --watchAll=false --silent",
    "eject": "craco eject",
    "test-watch": "craco test --silent",
    "pre-build": "npm run generate-version && npm run generate-browser-sunsetter",
    "generate-version": "generate-version -o ./public/version.json",
    "generate-browser-sunsetter": "generate-browser-sunsetter -o ./public/browser-sunsetter.js"
  }
}
``` 
This could be centralised into a single CLI project for common commands such as start/build/test. Optionally, we could look to rollup the `generate-version` and `generate-browser-sunsetter` tasks as a pre-build file that's part of the core ui package. 

**Goals**

- [x] Created a new repo called `@ricado/react-scripts` to hold our common App config.
- [x] Abstract the libraries `react-scripts` and `@craco/craco` away. Making them dependencies for our new project.
- [x] Centralise the craco config.
- [x] Create a `ricado-scripts` CLI that implements same craco/react-scripts commands.
- [x] Generate browser sunsetter scripts and version file as part of build.

**Comment by ghost** [comment]
Added a couple of notes from conversation with Ash

**Comment by ashneilson** [comment]
@josh-biddick Couple of thoughts for ya bro:

1) If ```version.json``` is needed by ```@ricado/core-ui``` then it would be great to have core-ui provide the build step somehow to generate this file?

2) I definitely reckon ```generate-browser-sunsetter``` could be moved within ```@ricado/react-scripts``` since it's would make sense to run this before a **build** or **start** command.

**Comment by ghost** [comment]
@ashneilson Hey bro. Just wanted to let you know that I'm not 100% comfortable that the solution of abstracting `craco` + `react-scripts` away into another library is going to benefit us in the long term. I'm starting to feel like it may become dificult for us to manage and would be more inclined to look at a "tailored" solution specifically for RICADO. Although `react-scripts` covers the bases for a majority of our apps requirements, anything could happen in future and we would always be at the liberty of how quickly they are to add new features - bearing in mind their team have to support 100's of thousands of developers writing React Apps. These limitations are becoming more apparent to me now as we're currently in the process of introducing new ES6 features which may or may-not be supported by `create-react-app`.

Ultimately I think I would be happier to build a type of "Build Chain" that allows us the flexibility to implement Webpack/ESLint/Jest etc the way we want. I looked at forking `react-scripts` and tweaking it for our needs but I don't understand completely how tweaks could have impact in other places.

Personally I think having developing/owning our own build tool could be a way for us to simplify our Gen4 App configuration, developing a better understanding of our internal tools and allow us to be faster at introducing new features,. 

Keen to hear what you think or if you want to have a chat about it in more detail in person.

**Comment by ghost** [comment]
@ashneilson Just to keep the ball rolling with this. I've had a think over the weekend on how we could acheive a more "scalable" approach to keeping all our config/CLI/dependencies inline. Ideally, I like the idea of not having to be dependent on a third-party (e.g. Create React App) for the way we build and bundle projects at RICADO. I think there is definately still value if that's what we decided on but we would need to weigh that up against how much flexibility that gains us.

One promising option is the `@rushstack/heft` project - https://rushstack.io/pages/heft/overview/

The idea being that you create custom "rigs" which are basically collections of configs/tools/dependencies that are pieced together to and executed by a Build Runner (Heft). 

Here's an example of a rig for a "web library" - https://github.com/microsoft/rushstack/tree/master/rigs/heft-web-rig

They make use of a package called `@rushstack/rig-package` which eliminates the need for multiple configurations copies across projects. I'm thinking we could define our own rig that would contain our Dependencies, Webpack Config, ESLint rules and CLI in one place.

I'm currently looking into this, so I'll update as I make more progress.

**Comment by ashneilson** [comment]
@josh-biddick I agree with you on this one. This has been my preference for a long time - great to be aligned on this 🙂 

There is a big part of me that would like to weigh up the complexity required within each App. Chances are most Apps will be the same utilizing the same dependencies - with a few differences where some Apps want extra dependencies to do something unique.

If we can achieve a good outcome that doesn't involve a lot of other 3rd party tools, I'd feel like that has great value for us as we are building our own tooling rather than configuring / tweaking a 3rd party tool to achieve the same outcome. In some cases you can end up spending just as much (if not more time) using the 3rd party tool long term 😆 

I'd say we need very little customization for each App - pretty much all of them will use the same ESLint rules, Webpack Config and Babel preferences / plugins. The more we simplify this down to our one package that provides the "guts" of each Gen 4 App, the easier it will be to maintain each App and fight npm / package battles mostly in the one package rather than in each App.

We could draw out a little diagram of how this could be simplified on paper so we're both on the same page about implementing this?

**Comment by ghost** [comment]
@ashneilson Good to hear man. Currently I'm going through the process of identifying what specific Webpack plugins/loaders our apps actually need and comparing against the `react-scripts` configuration. I've got a couple of PR's in progress which I was going to assign to you once I was ready but you can watch the progress of them here:

https://github.com/ricado-group/js-heft-web-rig/pull/1 - A new project containing shared rig config.
https://github.com/ricado-group/gen4-accounts-web/pull/49 - Testing the result of the above project.

Already showing some cool results, such as reducing the Webpack build times down to around 20s. Although, I haven't applied all the optimisations yet (e.g. Terser/CSS Optimizer etc). Also chatting with the main developer at `@rushstack` and he's been pretty quick getting back to me.

I think we'll be able to achieve a good outcome here with most of our tools being rolled up in one place. For now Webpack is keeping me pretty well entertained.

Also happy if you wanna sit down and get the finger painting set out :)

**Comment by ashneilson** [comment]
@josh-biddick I figured I'd close this issue as we're planning to deprecate this Repo anyhow :)
