### ISSUE TITLE
Bugsnag config

### ISSUE THREAD

**Issue by michaelpeterlee** [ricado-group/cra-template#13]
PROBLEM
Cannot `npm start` due to `defaultBugsnagConfig` not being exported from `@ricado/core-ui`.

STEPS TO REPRODUCE
```
npm login
npx create-react-app my-app --template @ricado/cra-template
npm start
```

**Comment by ghost** [comment]
This repo is being archived as we no longer use `create-react-app` for new Gen 4 apps.
