### ISSUE TITLE
SASS dependencies missing

### ISSUE THREAD

**Issue by michaelpeterlee** [ricado-group/cra-template#14]
PROBLEM
Cannot npm start due to missing SASS config/dependencies.

STEPS TO REPRODUCE
```
npm login
npx create-react-app my-app --template @ricado/cra-template
npm start
```

I resolved missing SASS dependencies  `npm install sass --save-dev`, however it still fails to parse less with error, below.

```
Failed to compile.

./src/index.less (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-9-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-9-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-9-4!./src/index.less)

.searchInputIcon(@input-height-base, @font-size-base);
^
Operation on an invalid type
      Error in /Users/mike/Desktop/workspace/ricado/gen4-packhouse-reporting-web/node_modules/antd/lib/input/style/search-input.less (line 23, column 0)
```

**Comment by michaelpeterlee** [comment]
Re: craco.config.js

https://github.com/DocSpring/craco-less asserts we should use https://github.com/DocSpring/craco-antd

**Comment by michaelpeterlee** [comment]
Tried `craco-antd` without success also. I simply copied `gen4-admin-web` and will port to this latest version once it's fixed.

**Comment by ghost** [comment]
This repo is being archived as we no longer use `create-react-app` for new Gen 4 apps.
