### ISSUE TITLE
Update PointProvider in AppProviders.tsx

### ISSUE THREAD

**Issue by ashneilson** [ricado-group/cra-template#3]
It appears the ```PointProvider``` now comes from **@ricado/points-service** rather than **@ricado/core-ui**

**Comment by ashneilson** [comment]
![image](https://user-images.githubusercontent.com/35913512/117380869-d1e90d80-af2e-11eb-928b-f64a8c24e7c5.png)

**Comment by ghost** [comment]
This should be resolved in [Release 1.2.4](https://github.com/ricado-group/cra-template/releases/tag/1.2.4)
