### ISSUE TITLE
Update Template to include REACT_APP_PROVIDER_ID in .env example

### ISSUE THREAD

**Issue by ashneilson** [ricado-group/cra-template#4]
It appears the variable ```REACT_APP_PROVIDER_ID``` should be included in the .env example (and reflected in the README.md).

This could be defaulted to the RICADO Provider ID since this is the typical use case when creating an App from this Template.

**Comment by ghost** [comment]
This should be resolved in [Release 1.2.4](https://github.com/ricado-group/cra-template/releases/tag/1.2.4)
