### ISSUE TITLE
Reduce app build times

### ISSUE THREAD

**Issue by ghost** [ricado-group/cra-template#9]
The newer Gen 4 UX Apps based on core-ui and cra-ricado take a very long time to build!
We need to work through the process of getting the build time down to a smaller figure.
Ideally the build times would line up with the older Gen 4 UX Apps which also use the Terser Webpack Plugin

**Comment by ghost** [comment]
@ashneilson I've done some digging into this today and have found 2 potential culprits to the long build times. I'll post by findings below:

**Accounts App**
Craco build 3.4.4 - **1.13s**
React Scripts build 3.4.4 - **50s**
React Scripts build 4.0.3 - **1.44s**

**Test CRA**
(No Third Party) React Scripts build - **19s**
![image](https://user-images.githubusercontent.com/74222743/119755744-9b336100-bef6-11eb-97f6-c18ab80805de.png)

**Test CRA**
(AntD) React Scripts build - **40s**
![image](https://user-images.githubusercontent.com/74222743/119755258-d2edd900-bef5-11eb-9aff-f93e2690dc7e.png)

**Test CRA**
(AntD + @ant-design/icons) React Scripts build - **49s**
![image](https://user-images.githubusercontent.com/74222743/119755226-c4072680-bef5-11eb-920d-f6c3e0a9a78f.png)

**Test CRA**
(AntD + @ant-design/icons + @ricado/api-client) React Scripts build - **57s**
![image](https://user-images.githubusercontent.com/74222743/119755333-f31d9800-bef5-11eb-8cb8-91648e74d1b7.png)

**Test CRA**
(AntD + @ant-design/icons + @ricado/api-client + lodash) React Scripts build - **58s**
![image](https://user-images.githubusercontent.com/74222743/119755368-06c8fe80-bef6-11eb-8e5a-9bc4add43e3d.png)

**Test CRA**
(AntD + @ant-design/icons + @ricado/api-client + lodash + react-query) React Scripts build - **53s**
![image](https://user-images.githubusercontent.com/74222743/119755431-22340980-bef6-11eb-860d-8c3e832986ba.png)

**Test CRA**
(AntD + @ant-design/icons + @ricado/api-client + lodash + react-query + @ricado/core-ui) React Scripts build - **2.08s**
![image](https://user-images.githubusercontent.com/74222743/119755472-32e47f80-bef6-11eb-9f84-2c7c234f506a.png)

**Test CRA**
(AMCharts + AntD) React Scripts build - **2.50s**
![image](https://user-images.githubusercontent.com/74222743/119755194-b782ce00-bef5-11eb-9b65-e640d99660fc.png)

**Comment by ghost** [comment]
@ashneilson My suspicion as to why `@ricado/core-ui` is blowing out the build time and bundle size is due to the package `zxcvbn` that we are using for checking password validity:
![image](https://user-images.githubusercontent.com/74222743/119756019-041ad900-bef7-11eb-9771-d6f57ba610dc.png)
As you can see the overall size (non gzipped) does match up with the difference in bundle size before and after adding `@ricado/core-ui`

**Comment by ghost** [comment]
Another rather large library (marked as a dependency) is `react-spring` for which we are only using in a single animated component:

![image](https://user-images.githubusercontent.com/74222743/119757442-1138c780-bef9-11eb-9d29-d34734b4be87.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/74222743/119757604-46451a00-bef9-11eb-9735-966aec61e3c7.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/74222743/119757982-dd11d680-bef9-11eb-808b-1e0d5656f511.png)

**Comment by ghost** [comment]
@ashneilson I think the biggest win here would be to exclude `zxcvbn` from the `dependencies` of Core UI. 

A couple of options could include:

- Include it only where it is used (i.e. the Accounts Web app). This will drop build times for other apps but not for Accounts Web.
- Add it as an `optionalDependency` so that only apps that use it will have their build times affected. See https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies for the pros/cons of this approach.
- Provide an API endpoint to do the heavy lifting and exclude it from the front-end code altogether. 

Could you please advise on one of these options?

**Comment by ashneilson** [comment]
@josh-biddick I agree with the process of moving ```zxcvbn``` to Accounts Web since that is the only place this will ever be utilized.

I assume some particular components and state could also be moved from ```core-ui``` to Accounts Web as a part of that process?

**Comment by ashneilson** [comment]
@josh-biddick I feel this issue could also be closed as we've reduced the bundle size of other Apps by removing the need for `zxcvbn` in Core UI
